config/routes.rb
Rails.application.routes.draw do
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/docs' => 'docs#index'
  post '/docs/uploading' => 'docs#uploading'
  get '/docs/fetch_all' => 'docs#fetch_all', as: 'root'
  get '/docs/:id/download' => 'docs#download', as: 'docs_download'

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user

  attr_accessor :uploaded_file

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :docs, dependent: :destroy
  has_secure_password

  validates :email, uniqueness: true, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, length: {:within => 6..40}, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user 

  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def require_user 
    redirect_to '/login' unless current_user 
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

  before_action :require_user

  def fetch_all
    @doc = Doc.new
    @docs = User.find(session[:user_id]).docs
  end

  def download
    name = Doc.find(params[:id]).name
    path = File.join(Rails.root, "file_storage", session[:user_id].to_s, name)
    send_file(path)
  end

  def uploading
    @doc = Doc.new
    @doc.user_id = session[:user_id]
    @doc.name = params["doc"]["uploaded_file"].original_filename
    file_path = File.join(Rails.root, 'file_storage', session[:user_id].to_s, @doc.name)
    f = File.open(file_path, 'wb')
    f.write params["doc"]["uploaded_file"].tempfile.read
    if !@doc.save
      redirect_to root_path :flash => { :upload_error => @doc.errors.full_messages.join(', ') }
    else
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
  end 
  
  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path, :flash => { :auth_error =>  "Invalid username or password"}
    end 
  end 

  def destroy 
    session[:user_id] = nil 
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params) 
    if @user.save 
      session[:user_id] = @user.id 
      Dir.mkdir "#{Rails.root}/file_storage/#{session[:user_id].to_s}"
      redirect_to root_path
    else 
      redirect_to signup_path, :flash => { :auth_error => @user.errors.full_messages.join(', ') }
    end
  end
  

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/docs/fetch_all.html.erb
</br> </br>
<table>
<% @docs.each do |doc| %>
      <tr>
        <td><%= link_to doc.name, docs_download_path(doc) %></td>
      </tr>
    <% end %>
</table>

</br> </br>
<%= form_for @doc, url: {:controller => "docs",:action => "uploading",:method => :post}, :html => {:multipart => true}  do |f| %>
  <%= f.file_field :uploaded_file %>
  <%= f.submit "Submit" %>
<% end %>

</div>
</div>

app/views/docs/index.html.erb
<%= form_for(@doc) do |f| %>
  <%= f.file_field :uploaded_file %>
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <link href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  

  <body>

    <div class="header">
      <div class="container">
        <%= link_to root_path do %>
          <img src="http://s3.amazonaws.com/codecademy-content/courses/rails-auth/img/fotofoto-logo.svg" width="80" height="80"> RapidShare
        <% end %>

        <div class="nav pull-right">
          <% if current_user %> 
  <ul> 
    <li><%= current_user.email %></li> 
    <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
  </ul> 
<% else %> 
  <ul> 
    <li><%= link_to "Login", 'login' %></a></li> 
    <li><%= link_to "Signup", 'signup' %></a></li> 
  </ul> 
<% end %>
          
        </div>
      </div>
    </div>

    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<% flash.each do |key, value| %>
   <%= content_tag :div, value, class: "flash_#{key}" %>
<% end %>

<div class="login">
  <div class="container">
    <div class="form">
    <h1>Sign up</h1>
    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password (min 6 characters)" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>
    </div>
  </div>
</div>